import {build} from 'esbuild';
import {createHash} from 'node:crypto';
import {readFile, writeFile, mkdir, copyFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
await build({
  absWorkingDir: root,
  entryPoints: ['frontend/dashboard.jsx'],
  bundle: true,
  minify: true,
  outdir: 'static/dist',
  entryNames: 'dashboard',
  define: {'process.env.NODE_ENV': '"production"'},
  logLevel: 'info',
});

// Serve the supplied brand artwork locally, preserving the original files.
const logos = ['fh2xhikcentral.png', 'logohikcentral2.png', 'logofh22.png'];
await mkdir(new URL('../static/brand/', import.meta.url), {recursive: true});
for (const logo of logos) {
  await copyFile(new URL(`../icons/${logo}`, import.meta.url), new URL(`../static/brand/${logo}`, import.meta.url));
}

// Changing an asset changes its URL, even when browsers retain an older copy.
const files = ['dist/dashboard.js', 'dist/dashboard.css', 'admin.js', 'admin.css', ...logos.map(logo => `brand/${logo}`)];
const versions = {};
for (const file of files) {
  versions[file] = createHash('sha256')
    .update(await readFile(new URL(`../static/${file}`, import.meta.url)))
    .digest('hex').slice(0, 12);
}
await writeFile(new URL('../templates/_assets.html', import.meta.url),
  '{# Generated by npm run build. Commit alongside static/dist/. #}\n' +
  '{% set versions = ' + JSON.stringify(versions, null, 2) + ' %}\n' +
  "{% macro url(filename) -%}{{ url_for('static', filename=filename, v=versions[filename]) }}{%- endmacro %}\n"
);
